[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Networks
[rpc_endpoints]
lisk-sepolia = "https://rpc.sepolia-api.lisk.com"
base-sepolia = "https://sepolia.base.org"
mainnet = "https://eth.llamarpc.com"

[etherscan]
lisk-sepolia = { key = "${LISK_ETHERSCAN_API_KEY}", url = "https://sepolia-blockscout.lisk.com/api" }
base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Test settings
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = true

# CI profile for faster compilation
[profile.ci]
fuzz = { runs = 10 }
invariant = { runs = 5, depth = 5 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
